### ISSUE TITLE
Problem with LFS images as attachments not showing for a CI pipeline publishing content to Confluence

### ISSUE THREAD

**Issue by AbianG** [git-lfs/git-lfs#4342]
**Describe the issue**
I am creating a POC for a documentation-as-code project: Using a github repo as the repository for Git and Github LFS to upload the images and large files to prevent bloating the repo itself. I then use github actions to automatically publish documentation to a private Confluence using [mark](https://github.com/kovetskiy/mark). But I have some problems:

- The LFS upload seems to be inconsistent, sometimes the pipeline will fail because the attachment could not be created. 

- Even when it works and mark gives no errors, attachments do not show later in Confluence. Whereas without LFS they did show/updated consistently
- I do not seem to be able to see the diferent versions of an image/file saved in LFS (git blame only seems to show one version and I can't see the different versions in the repo's webpage)

**System environment**
MacOs Catalina 10.15.6. Pipeline config:  
```
# This the basic CI pipeline

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    container: kovetskiy/mark:latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run hello message
        run: echo Integrating into Confluence

      # Runs a set of commands using the runners shell
      - name: Run integration
        run: |
          for file in $(find -type f -name '*.md'); do
            echo "> Sync $file";
            mark -u ${{ secrets.MARK_USER }} -p ${{ secrets.MARK_PASS }} -b ${{ secrets.MARK_URL }} -f $file || exit 1;
            echo;
          done
```

**Output of `git lfs env`**
```
git-lfs/2.12.1 (GitHub; darwin amd64; go 1.15.3)
git version 2.23.0

Endpoint=https://github.com/AbianG/AID_POC.git/info/lfs (auth=basic)
LocalWorkingDir=/Users/abianrodriguez/repos/sre-aid-poc-gh/AID_POC
LocalGitDir=/Users/abianrodriguez/repos/sre-aid-poc-gh/AID_POC/.git
LocalGitStorageDir=/Users/abianrodriguez/repos/sre-aid-poc-gh/AID_POC/.git
LocalMediaDir=/Users/abianrodriguez/repos/sre-aid-poc-gh/AID_POC/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/abianrodriguez/repos/sre-aid-poc-gh/AID_POC/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/abianrodriguez/repos/sre-aid-poc-gh/AID_POC/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_ASKPASS=/Applications/VSCodium.app/Contents/Resources/app/extensions/git/dist/askpass.sh
GIT_EXEC_PATH=/usr/local/git/libexec/git-core
VSCODE_GIT_ASKPASS_MAIN=/Applications/VSCodium.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
VSCODE_GIT_ASKPASS_NODE=/Applications/VSCodium.app/Contents/Frameworks/VSCodium Helper (Renderer).app/Contents/MacOS/VSCodium Helper (Renderer)
VSCODE_GIT_IPC_HANDLE=/var/folders/31/g2f1gp293mb0dls12y8zy3g80000gn/T/vscode-git-179e33bdc3.sock
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
Attachments using LFS have somehow worked the first time, adding more inconsistency.
