### ISSUE TITLE
Github Actions: Unable to locate executable file: git-lfs

### ISSUE THREAD

**Issue by AbianG** [git-lfs/git-lfs#4346]
**Describe the issue**
(My last issue got closed before I could get all up and running, so I have to open a new one, sorry about that) 
I am creating a POC for a documentation-as-code project: Using a github repo as the repository for Git and Github LFS to upload the images and large files to prevent bloating the repo itself. I then use github actions to automatically publish documentation to a private Confluence using mark. 

* As pointed out, I corrected the pipeline .yml adding `lfs: true` parameter to my `actions/checkout@v2` action.
    * Problem is, after this I get the following error: `Unable to locate executable file: git-lfs. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`
        * It seems that git lfs is not installed in the remote repository, but that´s strange, it is installed in the local one, and tracked uploaded files show the `Stored with Git LFS` text. Also, the visual diff of these images is not working, and I understand it should. 

**System environment**
MacOs Catalina 10.15.6. Pipeline config:
```
# This the basic CI pipeline

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    container: kovetskiy/mark:latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: # This is so the Pipe loads the LFS-tracked files
          lfs: true  

      # Runs a single command using the runners shell
      - name: Run hello message
        run: echo Integrating into Confluence

      # Runs a set of commands using the runners shell
      - name: Run integration
        run: |
          for file in $(find -type f -name '*.md'); do
            echo "> Sync $file";
            mark -u ${{ secrets.MARK_USER }} -p ${{ secrets.MARK_PASS }} -b ${{ secrets.MARK_URL }} -f $file || exit 1;
            echo;
          done
```
